### ISSUE TITLE
Planning a serialization format for EGM constants.

### ISSUE THREAD

**Issue by sorlok** [enigma-dev/lgmplugin#29]
I'm operating under the assumption that the EGM file format doesn't currently save/load constants. (The tests I've done seem to indicate this.) Also, I know that Robert wants to add configurations ("All Configurations", "Default", "Windows", etc.).

Why not just use INIs? For example:

```
[All Configurations]
some_string = "This is a test string"
some_float = 2.10

[Default]
some_string = "This is another test string"
some_other_float = 100

[Windows]
some_string = "This is a Windows string"
some_other_float2 = 300
```

This seems to match the "Configurations" format pretty well. Any thoughts?

**Comment by RobertBColton** [comment]
@sorlok An update to this is that LGM now handles GMK/GMX multiple configs and constants just fine. The EGM format just needs fixed up now.
http://enigma-dev.org/forums/index.php?topic=2269.msg24423#new

**Comment by sorlok** [comment]
@RobertBColton  Great! Glad to hear that GM* is working, and looking forward to (eventual) EGM support. Thanks!

**Comment by RobertBColton** [comment]
Closing as #82 covers the EGM format now being disabled due to incompleteness and user frustration. Ultimately, if we get to doing it for LGM after RGM, the plugin will use the new libEGM format from the main enigma-dev repo which is CI tested and prevents future issues. It already has support for constants, which are now going to be macros actually, like GMS.
