### ISSUE TITLE
library 'compileEGMf' error but Architecture: x86 and ./rebuildcompiler returns Error 1

### ISSUE THREAD

**Issue by probe0** [enigma-dev/lgmplugin#58]
https://github.com/enigma-dev/enigma-dev/releases/tag/v0.0.5.0
Download ENIGMA-Portable.exe
Run as administrator

The exact error is: Unable to load library 'compileEGMf': Native library (win32-x86/compileEGMf.dll) not found in resource path ([file:/D:/games/make_games/ide/ENIGMA/enigma-dev/plugins/enigma.jar])

Run [git-bash.bat] as administrator.
JAVA JAR error: https://pastebin.com/2CDqcciS
MAKE error: https://pastebin.com/Hr7Adihd
Unable to do ./rebuildcompiler

It appears the ENIGMA Plugin has encountered an issue: ENIGMA error (https://pastebin.com/Ptnrp7J9)
Architecture: x86

Run [git-bash.bat] as administrator.
$ gcc -dumpversion
4.8.2

$ gcc -dumpmachine
i686-w64-mingw32

$ gcc -dumpspecs
https://pastebin.com/aW9K8315

https://github.com/enigma-dev/lgmplugin/issues/51#issuecomment-251747114
https://dl.dropboxusercontent.com/u/14890209/dev/libcompileEGMf.dylib.zip
Error (404)
We can't find the page you're looking for.

**Comment by RobertBColton** [comment]
The dylib you linked has nothing to do with this error, that's the version of the compileEGMf dll on Mac. On Windows it's a `.dll`, on Mac it's a `.dylib`, and on Linux it's an `.so` because that's the convention for those platforms.

It seems it is unable to load compileEGMf.dll due to the make error:
```
.eobjs/./backend/ideprint.o: file not recognized: File format not recognized
```
Please try deleting `enigma-dev/CompilerSource/.eobjs` and then try again. That folder is where gcc puts the compiled binaries of the compiler source code. I have not actually seen this error before, but this comment seems relevant:
https://stackoverflow.com/a/34733244/2734025

Also, is the Java you have installed also 32 bit? If you build the compileEGMf.dll as 32 bit then you have to run LateralGM with a 32 bit Java because JNA can not load a 32 bit dll in a 64 bit VM. If you have a 64 bit Java, then you can try to install a parallel 32 bit Java:
https://enigma-dev.org/docs/Wiki/Install:Parallel_Java

**Comment by probe0** [comment]
Better too much information than too little?

Deleted .eojbs and then
./rebuildcompiler: https://pastebin.com/Jd7drCgr
./rebuildexe: https://pastebin.com/FqFh8hQS


----Another error on top----
This error is actually dependent on Windows theme.
Ignore what comes after.
ENIGMA is functional.
PS: another issue when compiling sample games (#59)




But there was another error that I assumed was the result of a previous error, but appeared regardless:
https://pastebin.com/HqSEnAp3

java.lang.NullPointerException errors continually pop up.

In [settings.ini]:
idecommand="C:\Program Files (x86)\Java\jre1.8.0_171\bin\java.exe -jar -Xms256m -Xmx1000m"

If I change it back to [idecommand="java -jar -Xms256m -Xmx1000m"], the compileEGMf.dll error pops up again.

$ java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

./update: https://pastebin.com/LBkdEpiL

java -jar lateralgm.jar: https://pastebin.com/Lc59WZ53

Already had both installed:
Java 8 Update 171
Java 8 Update 171 (64-bit)
in Programs and Features.

**Comment by RobertBColton** [comment]
Yes, all of that information has been useful so far. And yeah, the XP style exceptions have to do with the native Windows look and feel. Even though you are on Windows 10, much of the Java Swing look and feel for Windows still uses the rendering code Sun wrote for XP. That said, I actually think this must be a bug. You could try Java 9 out, that's currently what I have installed. I did not see your issue on Java 1.8 myself and it doesn't occur in Java 1.9. You could also just go to File->Preferences and change the look and feel setting to something other than Windows, but if you don't want to I understand because the Swing look and feels are horrible looking.

Here's my Java version if it helps:
```
C:\Windows\System32>java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

C:\Windows\System32>
```

Also, I am working and actually making progress on a C++ IDE for ENIGMA. It's turning out pretty well and I'm hoping to be able to share more info about it with everybody soon.
