### ISSUE TITLE
Build possible without Eclipse?

### ISSUE THREAD

**Issue by rfht** [enigma-dev/lgmplugin#67]
Is there an alternative? I'm a little stuck trying to get this to work on OpenBSD... Unfortunately eclipse is gone since 2016. Can it be replaced with something else? Or can the build system accomodate to working just with OpenJDK?

A few hints would suffice; I'm happy to try to figure out the details.

**Comment by RobertBColton** [comment]
Hi! You could try #57 out which restructures the plugin to use Maven. Also, in case you are not already aware, there are already jars available on the releases page: https://github.com/enigma-dev/lgmplugin/releases

Other than that I can provide very little advice as I am focusing most of my personal efforts on getting the new RadialGM IDE into beta status. We are getting close to that point and I will be making more announcements as we do. Because of this, I am not putting hardly any attention into LGM or its plugin unless absolutely necessary.

I hope that helps, and wish you luck!

**Comment by RobertBColton** [comment]
Closing as resolved by #81 which adds Travis CI using the existing Makefile except using the standard Java compiler. If you need help with using the Makefile, look at the 3 simple steps done by the Travis script in the repo to build the jar. If you still would like to see other ways of building without Eclipse, consider contribution to #57 so that Apache Maven is supported. I hope that you will find this helpful!
